

public class CountryInfo
{
    public static string[] countryNames = {
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
    "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
    "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
    "Belarus", "Belgium", "Belize", "Benin", "Bermuda",
    "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
    "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon",
    "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad",
    "Chile", "China", "Colombia", "Comoros", "Congo",
    "Costa Rica", "Croatia", "Cuba", "Czech Republic", "Denmark",
    "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
    "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia",
    "Fiji", "Finland", "France", "Gabon", "Gambia",
    "Georgia", "Germany", "Ghana", "Greece", "Grenada",
    "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
    "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland",
    "India", "Indonesia", "Iran", "Iraq", "Ireland",
    "Israel", "Italy", "Jamaica", "Japan", "Jordan",
    "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan",
    "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia",
    "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
    "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
    "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
    "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
    "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
    "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman",
    "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea",
    "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Puerto Rico", "Qatar", "Republic of the Congo", "Romania", "Russia",
    "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
    "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal",
    "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovenia",
    "Solomon Islands", "Somalia", "South Africa", "South Korea", "Spain",
    "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland",
    "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste",
    "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
    "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
    "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
    "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
    };
    public static string[] countryCodes = {
     "AFG", "ALB", "DZA", "AND", "AGO",
    "ATG", "ARG", "ARM", "AUS", "AUT",
    "AZE", "BHS", "BHR", "BGD", "BRB",
    "BLR", "BEL", "BLZ", "BEN", "BMU",
    "BTN", "BOL", "BIH", "BWA", "BRA",
    "BGR", "BFA", "BDI", "KHM", "CMR",
    "CAN", "CPV", "CYM", "CAF", "TCD",
    "CHL", "CHN", "COL", "COM", "COG",
    "CRI", "HRV", "CUB", "CZE", "DNK",
    "DJI", "DMA", "DOM", "ECU", "EGY",
    "SLV", "GNQ", "ERI", "EST", "ETH",
    "FJI", "FIN", "FRA", "GAB", "GMB",
    "GEO", "DEU", "GHA", "GRC", "GRD",
    "GUM", "GTM", "GIN", "GNB", "GUY",
    "HTI", "HND", "HKG", "HUN", "ISL",
    "IND", "IDN", "IRN", "IRQ", "IRL",
    "ISR", "ITA", "JAM", "JPN", "JOR",
    "KEN", "KIR", "XKX", "KWT", "KGZ",
    "LAO", "LVA", "LBN", "LSO", "LBR",
    "LBY", "LIE", "LTU", "LUX", "MAC",
    "MDG", "MWI", "MYS", "MDV", "MLI",
    "MLT", "MHL", "MRT", "MUS", "MEX",
    "FSM", "MDA", "MCO", "MNG", "MNE",
    "MAR", "MOZ", "MMR", "NAM", "NRU",
    "NPL", "NLD", "NZL", "NIC", "NER",
    "NGA", "PRK", "MKD", "NOR", "OMN",
    "PAK", "PLW", "PSE", "PAN", "PNG",
    "PRY", "PER", "PHL", "POL", "PRT",
    "PRI", "QAT", "COG", "ROU", "RUS",
    "RWA", "KNA", "LCA", "VCT", "WSM",
    "SMR", "STP", "SAU", "SEN", "SRB",
    "SYC", "SLE", "SGP", "SVN", "SLB",
    "SOM", "ZAF", "KOR", "ESP", "LKA",
    "SDN", "SUR", "SWE", "CHE", "SYR",
    "TJK", "TZA", "THA", "TLS", "TGO",
    "TON", "TTO", "TUN", "TUR", "TKM",
    "TUV", "UGA", "UKR", "ARE", "GBR",
    "USA", "URY", "UZB", "VUT", "VEN",
    "VIE", "YEM", "ZMB", "ZWE"
    };
}
